apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: o46jkz4oo-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: o46jkz4oo-nodejs 
  name: o46jkz4oo-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: o46jkz4oo-nodejs 
